apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-firefox
spec:
  replicas: 2
  selector:
    app: selenium-node-firefox
  template:
    metadata:
      name: selenium-node-firefox
      labels:
        app: selenium-node-firefox
    spec:
      containers:
      - name: selenium-node-firefox
        image: docker.io/selenium/node-firefox
        ports:
        - containerPort: 5900  
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: __IP_ADDRESS__
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
