apiVersion: v1
kind: Service
metadata:
  name: __APP__
  labels:
    app: __APP__
spec:
  type: LoadBalancer
  replicas: 1
  selector:
    app: __APP__
  template:
    metadata:
      labels:
        app: __APP__
    spec:
      containers:
      - name: __APP__
        image: __IMAGE__
        ports:
          - port: 8080
            containerPort: 8080
            targetPort: 8080
        env:
          - name: IC_GCE_AUTH
            value: __GCLOUD_KEY__
          - name: IC_GCE_PROJECT
            value: __GCLOUD_PROJECT_ID__
          - name: IC_GCE_IMAGE_BUCKET
            value: __GCLOUD_BUCKET__
          - name: IC_API_KEY
            value: __IC_API_KEY__
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
